version: "3.2"
services:
  https-portal:
    image: basip/link-web-proxy:${IMAGE:-latest}
    container_name: link-web-proxy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      DOMAINS: "$HTTPS_DOMAIN[issue_mode=$HTTPS_MODE,proxy_to=http://app:8000]"
    volumes:
      - app-ssl-certs:/var/lib/https-portal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  app:
    image: basip/link-app:${IMAGE:-latest}
    container_name: link-app
    restart: always
    env_file:
      - ".env"
    environment:
      - SHARED_SECRETS_PATH=/shared-secrets
    ports:
      - "8000:8000/tcp"
    depends_on:
      - redis
      - link-app-broker
      - link-device-broker
      - db
    networks:
      - link-internal
      - default
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - app-storage:/share/storage
      - system-logs:/var/log
      - device-broker-log:/var/log/device-broker:ro
      - shared-secrets:/shared-secrets
  redis:
    image: redis:6.2.4-alpine3.13
    container_name: link-redis
    restart: always
    ports:
      - "6379:6379/tcp"
    networks:
      - link-internal
    healthcheck:
      test: redis-cli -e PING || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  db:
    image: mysql:5.7.34
    container_name: link-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Qwerty12345
      - MYSQL_DATABASE=basip_link
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "3306:3306/tcp"
    networks:
      - link-internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--innodb-buffer-pool-size=2G", "--innodb-log-file-size=256M"]
  face-app:
    image: basip/link-face-app:${IMAGE:-latest}
    container_name: link-face-app
    restart: always
    ports:
      - "8089:80/tcp"
    networks:
      - link-internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  link-app-broker:
    image: basip/link-app-broker:${IMAGE:-latest}
    restart: always
    container_name: link-app-broker
    ports:
      - "127.0.0.1:1893:1893" #MQTT
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  link-device-broker:
    image: basip/link-device-broker:${IMAGE:-latest}
    restart: always
    container_name: link-device-broker
    environment:
      - LISTEN_PORT=48083
      - MOSQUITTO_CONFIG_PATH=/mosquitto/config
      - APP_ASSETS_PATH=/root/control-service/assets
      - SHARED_SECRETS_PATH=/shared-secrets/secrets.env
    ports:
      - "1883:1883"  #MQTT
      - "8883:8893" #MQTTS
    volumes:
      - app-ssl-certs:/certs
      - device-broker-settings:/mosquitto/config
      - device-broker-log:/var/log/supervisor
      - device-broker-app:/root/control-service/assets
      - shared-secrets:/shared-secrets:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  trace-collector:
    image: basip/link-log-trace-collector:${IMAGE:-latest}
    container_name: link-log-trace-collector
    restart: always
    depends_on:
      - redis
    networks:
      - link-internal
      - default
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  link-internal:
    internal: true

volumes:
  app-data: { external: true }
  system-logs: { external: true }
  app-storage: { external: true }
  app-ssl-certs: { external: true }
  device-broker-log: { }
  device-broker-settings: { }
  device-broker-app: { }
  shared-secrets: { }