version: "3.2"
services:
  autoheal:
    restart: always
    container_name: link-autoheal
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: basip/link-app:latest
    container_name: link-app
    restart: always
    ports:
      - "80:8000/tcp"
      - "6001:6001/tcp"
    depends_on:
      - redis
      - broker
      - db
    networks:
      - link-internal
      - default
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - app-storage:/share/storage
      - system-logs:/var/log
  redis:
    image: redis:6.2.4-alpine3.13
    container_name: link-redis
    restart: always
    ports:
      - "6379:6379/tcp"
    networks:
      - link-internal
    depends_on:
      - autoheal
    healthcheck:
      test: redis-cli -e PING || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  db:
    image: mysql:5.7.34
    container_name: link-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Qwerty12345
      - MYSQL_DATABASE=basip_link
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "3306:3306/tcp"
    networks:
      - link-internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--innodb-buffer-pool-size=2G", "--innodb-log-file-size=256M"]
  face-app:
    image: basip/link-face-app:latest
    container_name: link-face-app
    restart: always
    ports:
      - "8089:80/tcp"
    networks:
      - link-internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  broker:
    image: basip/link-broker:latest
    restart: always
    container_name: link-broker
    ports:
      - "61617:61617" #STOMP+SSL
      - "8161:8161"  #UI
      - "5672:5672"  #AMQP
      - "61613:61613" #STOMP
      - "1883:1883"  #MQTT
      - "61614:61614" #WS
      - "1884:1884"  #MQTT+SSL
    volumes:
      - broker-data:/opt/activemq/data
      - broker-app:/root/control-service/assets
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
networks:
  link-internal:
    internal: true

volumes:
  app-data: { external: true }
  system-logs: { external: true }
  app-storage: { external: true }
  broker-data: { external: true }
  broker-app: { }

