version: "3.2"
services:
  autoheal:
    restart: always
    container_name: link-autoheal
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: basip/link-app:${IMAGE:-latest}
    container_name: link-app
    restart: always
    ports:
      - "80:8000/tcp"
      - "6001:6001/tcp"
    depends_on:
      - redis
      - link-app-broker
      - link-device-broker
      - db
    networks:
      - link-internal
      - default
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - app-storage:/share/storage
      - system-logs:/var/log
      - device-broker-log:/var/log/device-broker:ro
      - sip-proxy-log:/var/log/sip-proxy:ro
  redis:
    image: redis:6.2.4-alpine3.13
    container_name: link-redis
    restart: always
    ports:
      - "6379:6379/tcp"
    networks:
      - link-internal
    depends_on:
      - autoheal
    healthcheck:
      test: redis-cli -e PING || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  db:
    image: mysql:5.7.34
    container_name: link-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=Qwerty12345
      - MYSQL_DATABASE=basip_link
    volumes:
      - app-data:/var/lib/mysql
    ports:
      - "3306:3306/tcp"
    networks:
      - link-internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--innodb-buffer-pool-size=2G", "--innodb-log-file-size=256M" ]
  face-app:
    image: basip/link-face-app:${IMAGE:-latest}
    container_name: link-face-app
    restart: always
    ports:
      - "8089:80/tcp"
    networks:
      - link-internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  link-app-broker:
    image: basip/link-app-broker:${IMAGE:-latest}
    restart: always
    container_name: link-app-broker
    ports:
      - "1893:1893" #MQTT
    networks:
      - link-internal
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  link-device-broker:
    image: basip/link-device-broker:${IMAGE:-latest}
    restart: always
    container_name: link-device-broker
    environment:
      - LISTEN_PORT=48083
      - MOSQUITTO_CONFIG_PATH=/mosquitto/config
      - APP_ASSETS_PATH=/root/control-service/assets
    ports:
      - "1883:1883"  #MQTT
      - "8883:8893" #MQTTS
    volumes:
      - device-broker-settings:/mosquitto/config
      - device-broker-log:/var/log/supervisor
      - device-broker-app:/root/control-service/assets
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  sip-proxy:
    image: basip/link-sip-proxy:${IMAGE:-latest}
    container_name: sip-proxy-app
    restart: always
    network_mode: host
    depends_on:
      - sip-proxy-db
    environment:
      - LISTEN_PORT=48080
      - KAMAILIO_CONFIG_PATH=/usr/local/etc/kamailio
      - APP_ASSETS_PATH=/root/control-service/assets
      - ARI_CONFIG_PATH=/usr/local/etc/ari-service
      - REDIS_HOST=127.0.0.1:6380
    volumes:
      - sip-proxy-app:/root/control-service/assets
      - sip-proxy-log:/var/log
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  sip-node:
    image: basip/link-sip-node:${IMAGE:-latest}
    container_name: sip-node-app
    network_mode: host
    restart: always
    environment:
      - LISTEN_PORT=48081
      - ASTERISK_CONFIG_PATH=/etc/asterisk
      - APP_ASSETS_PATH=/root/control-service/assets
    volumes:
      - sip-node-app:/root/control-service/assets
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
  sip-proxy-storage:
    image: redis:6.2.4-alpine3.13
    container_name: sip-proxy-storage
    restart: always
    ports:
      - "127.0.0.1:6380:6379/tcp"
    healthcheck:
      test: redis-cli -e PING || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - sip-proxy-storage:/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  link-internal:
    internal: true

volumes:
  app-data: { external: true }
  system-logs: { external: true }
  app-storage: { external: true }
  sip-node-app: { }
  sip-proxy-app: { }
  sip-proxy-log: { }
  sip-proxy-storage: { }
  device-broker-log: { }
  device-broker-settings: { }
  device-broker-app: { }
